/**
 * Lightweight multi-language profanity check (Edge-safe, no extra deps).
 *
 * Matching strategy:
 *  - Latin / Cyrillic scripts:  Unicode-aware "word boundary" regex (via
 *    lookarounds on \p{L}\p{N}), so e.g. "puta" matches as a word but
 *    "disputation" does not, and Vietnamese diacritics aren't treated as
 *    boundaries the way ASCII `\b` would.
 *  - CJK (Chinese / Japanese / Korean) and Arabic:  direct substring match,
 *    since those scripts don't use whitespace-delimited tokens.
 *  - Multi-word hate phrases / slogans: collapsed-string `.includes()`.
 *
 * Extended English leetspeak normalization still applies for the Latin list
 * only (0→o, 4→a, etc.).
 */

/** Shown when a comment (name/body/reply) fails the filter — server and client use the same copy. */
export const PROFANITY_COMMENT_WARNING =
  "Using bad language is not allowed. Don't be a fucking cunt. I use this to get jobs asshole. Thanks";

function escapeRegex(s: string) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Lowercase alphanumerics + common leetspeak substitutions for matching.
 * Leaves diacritics/Unicode intact (Vietnamese, Cyrillic, CJK).
 */
function normalizeForMatch(s: string): string {
  return s
    .toLowerCase()
    .replace(/0/g, "o")
    .replace(/1/g, "i")
    .replace(/3/g, "e")
    .replace(/4/g, "a")
    .replace(/5/g, "s")
    .replace(/7/g, "t")
    .replace(/@/g, "a")
    .replace(/\$/g, "s");
}

/** Collapse punctuation/spaces for phrase matching (Latin-only phrases). */
function collapseForPhrases(s: string): string {
  return normalizeForMatch(s)
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/*
 * ─── LATIN / CYRILLIC SINGLE-TOKEN BLOCKLIST ───────────────────────────────
 * Matched with a Unicode word boundary so diacritics count as "letter".
 * Covers: English, Spanish, Portuguese, French, German, Italian, Vietnamese,
 *         Russian (Cyrillic + common Latin transliterations),
 *         Hindi/Urdu/Tagalog/Turkish transliterations.
 */
const WORD_BLOCKED = [
  // ─── English: profanity / sexual ──────────────────────────────────────────
  "fuck",
  "fucker",
  "fucking",
  "fucked",
  "fucks",
  "fuckin",
  "fuckn",
  "fuk",
  "fucc",
  "phuck",
  "shit",
  "shits",
  "shitting",
  "shitty",
  "shite",
  "shiter",
  "bitch",
  "bitches",
  "bitchy",
  "biatch",
  "beotch",
  "asshole",
  "assholes",
  "asswipe",
  "asshat",
  "arsehole",
  "arse",
  "bastard",
  "bastards",
  "dick",
  "dicks",
  "dickhead",
  "dickheads",
  "dickwad",
  "cock",
  "cocks",
  "cocksucker",
  "cocksuckers",
  "cunt",
  "cunts",
  "cunty",
  "pussy",
  "pussies",
  "pussyhole",
  "slut",
  "sluts",
  "slutty",
  "whore",
  "whores",
  "hoe",
  "hoes",
  "twat",
  "twats",
  "wank",
  "wanker",
  "wankers",
  "bollocks",
  "piss",
  "pissed",
  "pisser",
  "crap",
  "crappy",
  "damn",
  "goddamn",
  "goddamned",
  "hell",
  "douche",
  "douchebag",
  "motherfucker",
  "motherfuckers",
  "motherfucking",
  "mofo",
  "bullshit",
  "bs",
  "jackass",
  "prick",
  "pricks",
  "dumbass",
  "dumbfuck",
  "dipshit",
  "shithead",
  "shitbag",
  "cum",
  "cumming",
  "jizz",
  "blowjob",
  "handjob",
  "rimjob",
  "ballsack",
  "nutsack",
  "testicle",
  "testicles",
  "scrotum",
  "boner",
  "jerkoff",

  // ─── English: ableist / anti-LGBTQ+ ───────────────────────────────────────
  "retard",
  "retards",
  "retarded",
  "tard",
  "spaz",
  "spastic",
  "midget",
  "cripple",
  "fag",
  "fags",
  "faggot",
  "faggots",
  "faggy",
  "dyke",
  "dykes",
  "tranny",
  "trannies",
  "troon",
  "shemale",
  "ladyboy",

  // ─── English: sexual violence ─────────────────────────────────────────────
  "rape",
  "raping",
  "rapist",
  "rapists",

  // ─── English: anti-Black / African American ───────────────────────────────
  "nigger",
  "niggers",
  "nigga",
  "niggas",
  "niggah",
  "niggar",
  "niglet",
  "coon",
  "coons",
  "jigaboo",
  "jiggaboo",
  "pickaninny",
  "pickaninnies",
  "porchmonkey",
  "spearchucker",
  "darkie",
  "darkies",
  "darky",
  "sambo",
  "buckwheat",
  "tarbaby",
  "nignog",

  // ─── English: anti-Hispanic / Latino ──────────────────────────────────────
  "spic",
  "spics",
  "spick",
  "spicks",
  "wetback",
  "wetbacks",
  "beaner",
  "beaners",
  "greaser",
  "greasers",
  "dago",
  "dagos",
  "guido",
  "guidos",

  // ─── English: anti–East / Southeast Asian ─────────────────────────────────
  "chink",
  "chinks",
  "chinky",
  "chinkie",
  "gook",
  "gooks",
  "jap",
  "japs",
  "nip",
  "nips",
  "zipperhead",
  "zipperheads",
  "slopehead",
  "slopeheads",
  "slant",
  "slanteye",
  "slanteyes",
  "dothead",
  "ching",
  "chong",
  "chingchong",
  "flip",
  "flips", // Filipino slur in context; rare but documented

  // ─── English: anti–South Asian / Middle Eastern ───────────────────────────
  "paki",
  "pakis",
  "pakies",
  "raghead",
  "ragheads",
  "towelhead",
  "towelheads",
  "sandnigger",
  "sandniggers",
  "cameljockey",
  "cameljockeys",
  "hajji",
  "hadji",
  "hajjis",

  // ─── English: anti-Jewish ─────────────────────────────────────────────────
  "kike",
  "kikes",
  "hymie",
  "hymies",
  "sheeny",
  "shylock",
  "yid",
  "yids",
  "heeb",
  "heebs",

  // ─── English: Native / Indigenous ─────────────────────────────────────────
  "redskin",
  "redskins",
  "injun",
  "injuns",
  "squaw",
  "squaws",
  "eskimo",
  "eskimos",

  // ─── English: misc ethnic / supremacist ──────────────────────────────────
  "honky",
  "honkie",
  "honkies",
  "peckerwood",
  "peckerwoods",
  "wog",
  "wogs",
  "mick",
  "micks",
  "polack",
  "polacks",
  "kraut",
  "krauts",
  "limey",
  "limeys",
  "frog",
  "frogs", // anti-French slur in context
  "gringo",
  "gringos",
  "gyp",
  "gypped",
  "gypsy",
  "gypsies",
  "mongoloid",
  "mulatto",
  "mulattoes",
  "negress",
  "mudshark",
  "mudsharks",
  "shitskin",
  "shitskins",
  "wigger",
  "wigga",
  "wiggar",
  "coonass",

  // ─── Spanish (español) ───────────────────────────────────────────────────
  "puta",
  "putas",
  "puto",
  "putos",
  "puteada",
  "putear",
  "pendejo",
  "pendejos",
  "pendeja",
  "pendejas",
  "cabron",
  "cabrón",
  "cabrones",
  "cabrones",
  "cabrona",
  "mierda",
  "mierdas",
  "coño",
  "cono",
  "coños",
  "chingar",
  "chinga",
  "chingada",
  "chingado",
  "chingadera",
  "chingadazo",
  "chingón",
  "chingon",
  "chingones",
  "joder",
  "jodido",
  "jodida",
  "verga",
  "vergas",
  "pinche",
  "pinches",
  "gilipollas",
  "maricón",
  "maricon",
  "maricones",
  "maricas",
  "marica",
  "zorra",
  "zorras",
  "follar",
  "follando",
  "polla",
  "pollas",
  "chucha",
  "culero",
  "culeros",
  "culera",
  "güey",
  "guey",
  "mamón",
  "mamon",
  "mamadas",
  "mamada",
  "idiota",
  "imbécil",
  "imbecil",
  "cojones",
  "cojudo",
  "caraculo",
  "hijueputa",
  "tarado",
  "tarada",
  "mariconazo",
  "panocha",

  // ─── Portuguese (português) ──────────────────────────────────────────────
  "porra",
  "porras",
  "caralho",
  "caralhos",
  "foda",
  "fodas",
  "fodido",
  "fodida",
  "foder",
  "bosta",
  "bostas",
  "merda",
  "merdas",
  "cu",
  "cuzao",
  "cuzão",
  "cuzona",
  "viado",
  "viados",
  "bicha",
  "bichas",
  "piranha",
  "pica",
  "buceta",
  "bucetas",
  "xoxota",
  "xoxotas",
  "otário",
  "otario",
  "puta", // overlap w/ Spanish is fine
  "babaca",
  "babacas",
  "fdp",
  "arrombado",
  "arrombada",
  "corno",
  "cornos",
  "cornudo",
  "vagabundo",
  "vagabunda",

  // ─── French (français) ───────────────────────────────────────────────────
  "putain",
  "putains",
  "pute",
  "putes",
  "merde",
  "merdes",
  "connard",
  "connards",
  "connasse",
  "connasses",
  "salope",
  "salopes",
  "salop",
  "salopard",
  "enculé",
  "encule",
  "enculer",
  "enculés",
  "enculee",
  "enculée",
  "couille",
  "couilles",
  "bite",
  "bites",
  "chatte",
  "chattes",
  "nique",
  "niquer",
  "niquez",
  "nique",
  "pédé",
  "pede",
  "pédés",
  "pedes",
  "tapette",
  "tapettes",
  "batard",
  "bâtard",
  "bâtards",
  "fdp", // fils de pute
  "gouine",
  "gouines",
  "pouffe",
  "pouffiasse",

  // ─── German (Deutsch) ────────────────────────────────────────────────────
  "scheisse",
  "scheiße",
  "scheiß",
  "scheissdreck",
  "arsch",
  "arschloch",
  "arschlöcher",
  "arschlocher",
  "fotze",
  "fotzen",
  "schwuchtel",
  "schwuchteln",
  "hurensohn",
  "hurensöhne",
  "hurensohne",
  "wichser",
  "wichsen",
  "wixer",
  "wixxer",
  "verdammt",
  "verfickt",
  "ficken",
  "fickt",
  "fickst",
  "fick",
  "ficker",
  "schwanz",
  "schwänze",
  "schwanzlutscher",
  "bimbo",
  "neger",

  // ─── Italian (italiano) ──────────────────────────────────────────────────
  "cazzo",
  "cazzi",
  "cazzate",
  "stronzo",
  "stronza",
  "stronzi",
  "stronze",
  "vaffanculo",
  "fanculo",
  "figa",
  "fica",
  "fighe",
  "puttana",
  "puttane",
  "troia",
  "troie",
  "zoccola",
  "zoccole",
  "coglione",
  "coglioni",
  "minchia",
  "minchie",
  "porca",
  "incapace",
  "sfigato",
  "sfigata",
  "bastardo",
  "bastarda",
  "bastardi",

  // ─── Vietnamese (tiếng Việt) ─────────────────────────────────────────────
  // Diacritic forms — high-signal.
  "đụ",
  "địt",
  "đéo",
  "đéch",
  "đếch",
  "lồn",
  "cặc",
  "buồi",
  "cứt",
  "đĩ",
  "đm",
  "đmm",
  "đcm",
  "đcmm",
  "đméo",
  "đéo",
  "cl",
  "vcl",
  "vkl",
  "vcđ",
  "đbrr",
  "đbr",
  "óc chó", // phrase, also caught below
  // Toneless forms that are specific enough not to false-positive.
  "dit", // đ-less form of địt; not a common English token
  "dcm",
  "dmm",
  "vcl",
  "vkl",
  "clgt",
  "vlxx",

  // ─── Russian — Latin transliterations ────────────────────────────────────
  "huy",
  "huyam",
  "huya",
  "pizda",
  "pizdec",
  "pizdets",
  "blyad",
  "blyat",
  "bliad",
  "suka",
  "sukin",
  "yebat",
  "yebal",
  "yebanyi",
  "ebat",
  "ebal",
  "ebaniy",
  "ebanaya",
  "pidor",
  "pidoras",
  "pidorash",
  "mudak",
  "mudila",
  "govno",
  "goavno",
  "zhopa",
  "dolboeb",
  "dolboyob",
  "dolboyob",

  // ─── Russian — Cyrillic originals ────────────────────────────────────────
  "хуй",
  "хуя",
  "хуйня",
  "хуёво",
  "хуево",
  "пизда",
  "пизде",
  "пиздец",
  "пидор",
  "пидорас",
  "пидарас",
  "блядь",
  "блять",
  "бля",
  "сука",
  "суки",
  "сучка",
  "ебать",
  "ёбаный",
  "ебаный",
  "ебал",
  "ебаная",
  "мудак",
  "мудаки",
  "говно",
  "жопа",
  "долбоеб",
  "долбоёб",
  "хуесос",
  "ебанько",

  // ─── Hindi / Urdu — Latin transliterations ───────────────────────────────
  "chutiya",
  "chutiye",
  "chutia",
  "bhenchod",
  "behenchod",
  "bhenchodh",
  "bhosdike",
  "bhosdika",
  "bhosadi",
  "madarchod",
  "madharchod",
  "maaderchod",
  "mc",
  "bc",
  "gandu",
  "gaandu",
  "gand",
  "lauda",
  "laude",
  "lund",
  "lun",
  "randi",
  "raand",
  "harami",
  "kutta",
  "kutte",
  "kamina",
  "kaminey",
  "saala",
  "saali",
  "jhaatu",

  // ─── Tagalog / Filipino ──────────────────────────────────────────────────
  "puta", // overlap w/ Spanish
  "putang",
  "puke",
  "gago",
  "gaga",
  "tanga",
  "tangina",
  "tanginamo",
  "tarantado",
  "pakyu",
  "putragis",
  "lintik",
  "bobo",
  "boba",
  "leche",
  "ulol",

  // ─── Turkish (Türkçe) ────────────────────────────────────────────────────
  "siktir",
  "sikeyim",
  "sikik",
  "sikerim",
  "amına",
  "amina",
  "amcık",
  "amcik",
  "orospu",
  "piç",
  "pic",
  "göt",
  "got",
  "yarrak",
  "yarak",
  "pezevenk",
  "şerefsiz",
  "serefsiz",

  // ─── Indonesian / Malay ──────────────────────────────────────────────────
  "anjing",
  "anjir",
  "bangsat",
  "kontol",
  "memek",
  "tai",
  "bajingan",
  "babi",
  "goblok",
  "tolol",
  "jancok",
  "jancuk",
  "asu",
  "pepek",
  "pukimak",
  "cibai",
  "cibaii",
  "lanciao",

  // ─── Chinese pinyin / English-alphabet typings ───────────────────────────
  // Compound/unambiguous only — we deliberately skip bare "cao", "gan",
  // "ma", "ni", "ta" since those collide with English and names.
  "caonima",
  "caonimade",
  "caonm",
  "nimade",
  "nimabi",
  "tamade",
  "wocao",
  "wokao",
  "shabi",
  "shabie",
  "shabis",
  "shabee",
  "ganninliang",
  "ganniang",
  "gannimei",
  "wangbadan",
  "biaozi",
  "jibai",
  "jibbai",
  "chouxiezi",
  "nmsl", // 你妈死了
  "wcnm", // 我操你妈
  "tmd", // 他妈的
  "nmb", // 你妈逼
  "cnm", // 操你妈

  // ─── Japanese romaji ────────────────────────────────────────────────────
  "kuso",
  "kusottare",
  "kusoyaro",
  "kusoyarou",
  "kusogaki",
  "chikusho",
  "chikushou",
  "chinko",
  "chinpo",
  "chinchin",
  "chinpoko",
  "manko",
  "omanko",
  "bakayaro",
  "bakayarou",
  "baka",
  "bakatare",
  "aho",
  "ahou",
  "ahotare",
  "kichigai",
  "kutabare",
  "kuzu",
  "temee",
  "teme",
  "temē",
  "unko",
  "korosu",
  "shinee",
  "shinjimae",
  "fakku",
  "yariman",
  // NOTE: romaji "shine" (= die) collides with English "shine" — not blocked.

  // ─── Korean romanization ────────────────────────────────────────────────
  "ssibal",
  "ssipal",
  "sibal",
  "sipal",
  "shibal",
  "shipal",
  "ssibar",
  "sibar",
  "shibar",
  "ssiba",
  "shiba", // risky (dog breed) but common insult form — accept
  "ssipda",
  "gaesaekki",
  "gaesekki",
  "gaesaeki",
  "gaesaek",
  "kaesaekki",
  "kaessaeki",
  "jonna",
  "jolla",
  "jonnna",
  "byeongsin",
  "byungsin",
  "byeongshin",
  "byungshin",
  "byongsin",
  "michinnom",
  "michinnyun",
  "michinnyeon",
  "michinnyun",
  "michinsaekki",
  "jiral",
  "jiraljiral",
  "dakchyeo",
  "kkeojyeo",
  "jot",
  "jotna",
  "jotmanhan",
  "horosaekki",

  // ─── Vietnamese — toneless / English-alphabet typings ────────────────────
  // Keep only forms with low English collision; skip bare "cac", "cut",
  // "lon", "deo", "cak" etc. Phrases are handled in BLOCKED_PHRASES.
  "ditme",
  "ditmemay",
  "duma",
  "dumemay",
  "duconme",
  "dmcs",
  "conme",
  "conmemay",
  "concac",
  "conlon",
  "cailon",
  "caccho",
  "occho",

  // ─── Arabic transliterations ────────────────────────────────────────────
  "kosommak",
  "kosomak",
  "kosomk",
  "kossummak",
  "kosikhto",
  "kosokhtak",
  "kosem",
  "sharmoota",
  "sharmouta",
  "charmouta",
  "sharmouteh",
  "sharmoutah",
  "manyak",
  "manyook",
  "nayek",
  "neek",
  "neekommak",
  "nayikommak",
  "ibnkalb",
  "ibnelkalb",
  "ibnelmetnaka",
  "ayriffik",
  "zebi",
  "zbi",
];

/*
 * ─── CJK / ARABIC SUBSTRING BLOCKLIST ──────────────────────────────────────
 * These scripts don't use whitespace word boundaries; simple substring match
 * on the lowercased text. Keep entries long enough to avoid false positives
 * (e.g. we don't block bare 干 or bare 년).
 */
const SUBSTRING_BLOCKED = [
  // ─── Chinese (普通话 / 粵語, simplified + traditional) ───────────────────
  "肏",
  "操你",
  "操他",
  "操妈",
  "操你妈",
  "操你媽",
  "肏你妈",
  "肏你媽",
  "妈的",
  "媽的",
  "他妈的",
  "他媽的",
  "妈逼",
  "媽屄",
  "妈比",
  "媽比",
  "尼玛",
  "尼瑪",
  "泥马",
  "傻逼",
  "傻屄",
  "傻比",
  "煞笔",
  "煞筆",
  "二逼",
  "屌",
  "屌你",
  "屌佢",
  "屌他",
  "屌她",
  "鸡巴",
  "雞巴",
  "鸡八",
  "雞八",
  "鸡掰",
  "雞掰",
  "屄",
  "逼养",
  "逼樣",
  "狗屎",
  "狗日",
  "狗娘",
  "狗娘养",
  "狗杂种",
  "狗雜種",
  "婊子",
  "贱人",
  "賤人",
  "贱货",
  "賤貨",
  "小婊子",
  "王八蛋",
  "龟儿子",
  "龜兒子",
  "龟孙子",
  "龜孫子",
  "操你祖宗",
  "干你娘",
  "幹你娘",
  "去你妈",
  "去你媽",
  "去你的",
  "我操",
  "我肏",
  "卧槽",
  "臥槽",
  "我靠",
  "屁眼",
  "狗屁",
  "放屁",
  "贱逼",
  "賤屄",
  "烂货",
  "爛貨",
  "骚货",
  "騷貨",
  "娘炮",
  "死胖子",
  "滚蛋",
  "滾蛋",
  "滚犊子",
  "滾犢子",
  "死全家",
  "你妈死了",
  "你媽死了",
  "逼崽子",
  "屄崽子",

  // ─── Japanese (日本語) ───────────────────────────────────────────────────
  "くそ",
  "クソ",
  "糞",
  "ちんこ",
  "チンコ",
  "ちんぽ",
  "チンポ",
  "まんこ",
  "マンコ",
  "おまんこ",
  "オマンコ",
  "淫乱",
  "やりまん",
  "ヤリマン",
  "ばか",
  "バカ",
  "馬鹿",
  "あほ",
  "アホ",
  "阿呆",
  "しね",
  "死ね",
  "殺す",
  "ころす",
  "ぶっ殺す",
  "きちがい",
  "キチガイ",
  "気違い",
  "てめえ",
  "てめー",
  "てめぇ",
  "くたばれ",
  "クタバレ",
  "ファック",
  "畜生",
  "ちくしょう",
  "クソ野郎",
  "くそ野郎",
  "ぼけ",
  "ボケ",
  "かす",
  "カス",
  "屑",
  "変態",
  "へんたい",
  "ヘンタイ",
  "エロ",
  "ちんちん",
  "ちんぽこ",
  "うんこ",
  "ウンコ",

  // ─── Korean (한국어) ────────────────────────────────────────────────────
  "씨발",
  "시발",
  "씨팔",
  "시팔",
  "씨바",
  "시바",
  "씹",
  "ㅆㅂ",
  "ㅅㅂ",
  "좆",
  "좆같",
  "좆나",
  "존나",
  "졸라",
  "개새끼",
  "개새",
  "개년",
  "개자식",
  "미친놈",
  "미친년",
  "미친새끼",
  "병신",
  "븅신",
  "ㅂㅅ",
  "지랄",
  "엿먹어",
  "닥쳐",
  "꺼져",
  "보지",
  "자지",
  "니미",
  "니애미",
  "니애비",
  "느금마",
  "느그마",
  "호로새끼",
  "호로자식",
  "쌍년",
  "쌍놈",
  "싸가지",
  "개소리",
  "걸레",
  "창녀",
  "똥꼬",

  // ─── Arabic (العربية) ───────────────────────────────────────────────────
  "كس",
  "كسمك",
  "كسختك",
  "كس امك",
  "كس اختك",
  "زب",
  "زبر",
  "قحبة",
  "قحاب",
  "شرموطة",
  "شراميط",
  "احا",
  "أحا",
  "ابن الكلب",
  "ابن الشرموطة",
  "يا ابن الكلب",
  "منيك",
  "نيك",
  "نيكك",
  "نياك",
  "طيز",
  "خول",
  "معرص",
  "عرص",
  "عاهرة",
  "شاذ",
  "كافر",
  "ابن الحرام",
  "يا حيوان",
];

/*
 * ─── MULTI-WORD HATE PHRASES / SLOGANS ─────────────────────────────────────
 * Checked after collapsing spaces on the Latin-normalized text.
 */
const BLOCKED_PHRASES = [
  // English / neo-Nazi
  "white power",
  "heil hitler",
  "sieg heil",
  "blood and soil",
  "gas the jews",
  "gas the kikes",
  "jews will not replace us",
  "jews will not replace",
  "white genocide",
  "race traitor",
  "race traitors",
  "jungle bunny",
  "jungle bunnies",
  "porch monkey",
  "porch monkeys",
  "sand nigger",
  "sand niggers",
  "moon cricket",
  "moon crickets",
  "we wuz kangz",
  "we wuz kings",
  "small hats",
  "day of the rope",
  "camel jockey",
  "camel jockeys",
  "dirty jew",
  "dirty jews",
  "filthy jew",
  "filthy jews",
  "kill all jews",
  "kill all blacks",
  "kill all whites",
  "kill all muslims",
  "kill yourself",
  "kys",
  "go kill yourself",

  // Spanish
  "hijo de puta",
  "hija de puta",
  "hijos de puta",
  "hijas de puta",
  "la concha de tu madre",
  "chinga tu madre",
  "vete a la mierda",
  "me cago en",

  // Portuguese
  "filho da puta",
  "filha da puta",
  "vai tomar no cu",
  "vai se fuder",
  "vai se foder",
  "puta que pariu",

  // French
  "fils de pute",
  "fille de pute",
  "va te faire foutre",
  "va te faire enculer",
  "nique ta mere",
  "nique ta mère",

  // German
  "halts maul",
  "halt die fresse",
  "fick dich",
  "leck mich",
  "geh sterben",

  // Italian
  "figlio di puttana",
  "figlia di puttana",
  "vai a cagare",
  "porca puttana",
  "porco dio",

  // Vietnamese
  "con mẹ mày",
  "con me may",
  "chó đẻ",
  "cho de",
  "đồ chó",
  "do cho",
  "mẹ mày",
  "me may",
  "má mày",
  "ma may",
  "đầu buồi",
  "dau buoi",
  "óc chó",
  "oc cho",
  "du ma",
  "du ma may",
  "du me",
  "du me may",
  "dit me",
  "dit me may",
  "dit con me",
  "dit con me may",
  "do ngu",
  "do cho de",
  "cai lon me",
  "con di",
  "con di me",

  // Chinese pinyin (space-separated)
  "cao ni ma",
  "cao nimade",
  "cao ni mama",
  "cao ni dada",
  "cao ni ba",
  "ni ma de",
  "ni mei",
  "ta ma de",
  "ta mei",
  "wo cao",
  "wo kao",
  "gan ni niang",
  "gan ni ma",
  "gan ni ba",
  "gan ni mama",
  "gan ni laoshi",
  "gan ni lao mu",
  "wang ba dan",
  "sha bi",
  "er bi",

  // Japanese romaji (phrases)
  "baka yaro",
  "baka yarou",
  "kuso yaro",
  "kuso yarou",
  "busu yaro",
  "busu yarou",
  "shinde shimae",
  "shine yo",
  "kutabatte shimae",

  // Korean romanized (phrases)
  "ssi bal",
  "shi bal",
  "gae saekki",
  "gae sekki",
  "byeong sin",
  "byung sin",
  "mi chin nom",
  "mi chin nyun",
  "mi chin nyeon",
  "jot na",
  "jot ga",
  "nae ga jot",
  "dak cheo",
  "kkeo jyeo",
  "yeot meogeo",
  "yaet meogeo",

  // Arabic romanized (phrases)
  "kos ommak",
  "kos okhtak",
  "kos omak",
  "ibn el kalb",
  "ibn kalb",
  "ibn el sharmouta",
  "neek ommak",
  "neek okhtak",
  "ya ibn el",
  "ya manyak",
];

// Numeric / symbol hate codes (whole-token only).
const HATE_CODE_RE = /(?<![\p{L}\p{N}])(?:1488|8814|14\/88|88\/14)(?![\p{L}\p{N}])/u;

// Unicode-aware "word boundary" around each Latin/Cyrillic blocked word.
const WORD_PATTERN = new RegExp(
  `(?<![\\p{L}\\p{N}])(?:${WORD_BLOCKED.map(escapeRegex).join("|")})(?![\\p{L}\\p{N}])`,
  "iu"
);

export function isProfane(text: string): boolean {
  if (!text.trim()) return false;

  const normalized = normalizeForMatch(text);

  // 1. Latin/Cyrillic word-boundary match.
  if (WORD_PATTERN.test(normalized)) return true;

  // 2. Hate-code numeric match.
  if (HATE_CODE_RE.test(normalized)) return true;

  // 3. CJK / Arabic substring match on the raw-lowercased text
  //    (leetspeak substitutions are meaningless for these scripts).
  const lower = text.toLowerCase();
  for (const token of SUBSTRING_BLOCKED) {
    if (lower.includes(token)) return true;
  }

  // 4. Multi-word phrases after punctuation/space collapse.
  const collapsed = collapseForPhrases(text);
  if (!collapsed) return false;
  for (const phrase of BLOCKED_PHRASES) {
    if (collapsed.includes(phrase)) return true;
  }

  return false;
}

/** Joins optional display name, comment body, and reply @handle for profanity scanning (all share the same filter). */
export function combinedCommentText(parts: {
  name?: string | null;
  body?: string | null;
  reply_to_name?: string | null;
}): string {
  return [parts.name, parts.body, parts.reply_to_name]
    .map((s) => (typeof s === "string" ? s : ""))
    .join(" ");
}
